---
#Lanse kanj sou plizye server anmenm tan
- hosts: kanj

  become: yes

  tasks:

  - name: run kanj on zl servers
    docker_container:
      name: 'mysql-kanj'
      image: zldev/mysql:1.0.0
      env:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - "/opt/hms/mysql:/var/lib/mysql"
      published_ports:
        - "3307:3306"

  - name: copy structure.sql to servers
    copy: 
      src: ./{{ item }}
      dest: /opt/kanj/
    with_item:
      - ./id-structure.sql
      - ./insert-structure.sh
  
  - name: insert id structure to database
    shell: bash /opt/kanj/insert-structure.sh
    register: insert_result
  
  - debug: msg=={{ insert_result }}