---
#Lanse kanj sou plizye server anmenm tan
- hosts: kanj

  become: yes

  tasks:

  - name: run kanj on zl servers
    docker_container:
      name: 'mysql-kanj'
      image: zldev/mysql:1.0.0
      env:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - "/opt/hms/mysql:/var/lib/mysql"
      published_ports:
        - "3307:3306"