---
- hosts: kanj
  become: yes
  tasks:

    - name: rename docker-compose file on servers
      shell: chdir=/home/hms/hms-implementation/kanj-v101/ mv docker-compose.yml docker-compose.yml.101

    - name: copy docker-compose file
      copy:
        src: /home/ansible/ops/kanj-v102/docker-compose.yml
        dest: /home/hms/hms-implementation/

    - name: enable startid daemon
      shell: systemctl daemon-reload
    
    # - name: enable startid daemon
    #   shell: systemctl start startid

    - name: check docker-compose version
      shell: docker-compose --version

    - name: pull images with docker-compose
      shell: chdir=/home/hms/hms-implementation/kanj-v102/ docker-compose pull
      register: pull-kanj
    
    - debug: msg=={{ pull-kanj }}
    
    - name: launch kanj with docker-compose
      shell: chdir=/home/hms/hms-implementation/kanj-v101/ docker-compose up -d
      register: launch-kanj
    
    - debug: msg=={{ launch-kanj }}