---
- hosts: kanj
  become: yes
  tasks:
    - name: copy script on servers
      copy:
        src: ./{{ item }}
        dest: /opt/kanj/
      with_items:
        - update101.sh
        - update101.sql
    - name: update id database
      shell: bash /opt/kanj/update101.sh
      register: update_result
    
    - debug: msg=={{ update_result }}