- hosts: thomonde
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home/hms/hms-implementation/
    
    - name: copy docker-compose file 
      copy:
        src: /home/ansible/ops/kanj/docker-compose.yml-th
        dest: /home/hms/hms-implementation/docker-compose.yml