---
- hosts: kanj
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/hms/conf/
        - /opt/hms/conf/id/
        - /home/hms/hms-implementation/
        - /home/hms/hms-implementation/kanj-v101
    

    - name: copy id component to servers
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
      with_items:
        - {src: '/home/ansible/ops/kanj-v101/id/*', dest: '/opt/hms/conf/id/'}
        - {src: '/home/ansible/ops/kanj-v101/conf/startid.service', dest: '/etc/systemd/system/'}
        - {src: '/home/ansible/ops/kanj-v101/conf/startid.sh', dest: '/opt/hms/conf/'}
        - {src: '/home/ansible/ops/kanj-v101/docker-compose.yml', dest: '/home/hms/hms-implementation/kanj-v101/'}
        - {src: '/home/ansible/ops/kanj-v101/docker-compose.yml', dest: '/home/hms/hms-implementation/kanj-v101/'}
    
    - name: enable startid daemon
      systemd: 
        state: enable
        daemon_reload: yes
        name: startid
      
    - name: pull images with docker-compose
      shell: chdir=/home/hms/hms-implementation/kanj-v101/ docker-compose pull
      register: pull-kanj
    
    - debug: msg=={{ pull-kanj }}
    
    - name: launch kanj with docker-compose
      shell: chdir=/home/hms/hms-implementation/kanj-v101/ docker-compose up -d
      register: launch-kanj
    
    - debug: msg=={{ launch-kanj }}