---
- hosts: kanj
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/hms/conf/
        - /home/hms/hms-implementation/
        