---
- hosts: kanj
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/hms/conf/
        - /opt/hms/conf/id/
        - /home/hms/hms-implementation/
    

    - name: copy id component to servers
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
      with_items:
        - {src: '/home/ansible/ops/id/', dest: '/opt/hms/conf/id/'}

        