---
- hosts: kanj
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/hms/conf/
        - /opt/hms/conf/id/
        - /home/hms/hms-implementation/
        - /home/hms/hms-implementation/kanj-v101
    

    # - name: copy id component to servers
    #   copy:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest}}"
    #     mode: "{{ item.mode }}"
    #     remote_src: yes
    #   with_items:
    #     - { src: '/home/ansible/ops/kanj-v101/conf/id/', dest: '/opt/hms/conf/id/', mode: 777 }
    #     - { src: '/home/ansible/ops/kanj-v101/conf/startid.service', dest: '/etc/systemd/system/' }
    #     - { src: '/home/ansible/ops/kanj-v101/conf/startid.sh', dest: '/opt/hms/conf/startid.sh' }
    #     - { src: '/home/ansible/ops/kanj-v101/docker-compose.yml', dest: '/home/hms/hms-implementation/kanj-v101/' }
    
    - name: copy id component to servers
      copy: 
        src: '/home/ansible/ops/kanj-v101/conf/id/'
        dest: /opt/hms/conf/id/

    - name: copy startid.service 
      copy:
        src: /home/ansible/ops/kanj-v101/conf/startid.service
        dest: /etc/systemd/system/

    - name: copy startid.service 
      copy:
        src: /home/ansible/ops/kanj-v101/conf/startid.sh
        dest: /opt/hms/conf/

    - name: copy docker-compose file
      copy:
        src: /home/ansible/ops/kanj-v101/docker-compose.yml
        dest: /home/hms/hms-implementation/kanj-v101/

    - name: enable startid daemon
      shell: systemctl daemon-reload
    
    # - name: enable startid daemon
    #   shell: systemctl start startid

    - name: check docker-compose version
      shell: docker-compose --version

    # - name: pull images with docker-compose
    #   shell: chdir=/home/hms/hms-implementation/kanj-v101/ docker-compose pull
    #   register: pull-kanj
    
    # - debug: msg=={{ pull-kanj }}
    
    # - name: launch kanj with docker-compose
    #   shell: chdir=/home/hms/hms-implementation/kanj-v101/ docker-compose up -d
    #   register: launch-kanj
    
    # - debug: msg=={{ launch-kanj }}