---
- hosts: kanj
  become: yes
  tasks:
    - name : create required folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/hms/conf/
        - /opt/hms/conf/id/
        - /home/hms/hms-implementation/
    
    - name: copy id component to servers
      copy: 
        src: '/home/ansible/ops/kanj/conf/id/'
        dest: /opt/hms/conf/id/

    - name: copy startid.service 
      copy:
        src: /home/ansible/ops/kanj/conf/startid.service
        dest: /etc/systemd/system/

    - name: copy startid.service 
      copy:
        src: /home/ansible/ops/kanj/conf/startid.sh
        dest: /opt/hms/conf/

    - name: copy docker-compose file for lacollines
      hosts: lacollines
      copy:
        src: /home/ansible/ops/kanj/docker-compose.yml-lac
        dest: /home/hms/hms-implementation/docker-compose.yml

    - name: copy docker-compose file for thomonde
      hosts: thomonde
      copy:
        src: /home/ansible/ops/kanj/docker-compose.yml-th
        dest: /home/hms/hms-implementation/docker-compose.yml

    - name: enable startid daemon
      shell: systemctl daemon-reload
    
    # - name: enable startid daemon
    #   shell: systemctl start startid

    - name: check docker-compose version
      shell: docker-compose --version
      register: result

    - debug: msg=={{ result }}

    - name: pull images with docker-compose
      shell: chdir=/home/hms/hms-implementation/ docker-compose pull
      register: pull
    
    - debug: msg=={{ pull }}
    
    - name: launch kanj with docker-compose
      shell: chdir=/home/hms/hms-implementation/ docker-compose up -d
      register: launch
    
    - debug: msg=={{ launch }}

    - name: start startid
      shell: systemctl start startid
    